In [18]:
%pip install psycopg2-binary

6874.10s - pydevd: Sending message related to process being replaced timed-out after 5 seconds

Requirement already satisfied: psycopg2-binary in ./venv/lib64/python3.14/site-packages (2.9.13)

[notice] A new release of pip is available: 26.0.1 -> 26.2.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [19]:
import pandas as pd
from sqlalchemy import create_engine

# Conexión explícita usando psycopg2
engine = create_engine('postgresql+psycopg2://root:root@127.0.0.1:5433/ny_taxi')

# Probamos la conexión
engine.connect()
print("¡Conexión exitosa a PostgreSQL!")

¡Conexión exitosa a PostgreSQL!

In [20]:
# Leemos solo las primeras 100 filas (nrows=100)
df = pd.read_csv('yellow_tripdata_2021-01.csv', nrows=100)

# head() nos muestra las primeras 5 filas visualmente
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5

In [ ]:
# Usamos pandas (pd) para generar el esquema SQL.
# Le pasamos nuestra muestra (df), el nombre que queremos para la tabla ('yellow_taxi_data')
# y el motor de base de datos para que sepa qué "dialecto" de SQL usar (Postgres)
esquema_sql = pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine)

print(esquema_sql)

In [23]:
# Convertimos las columnas de texto a objetos datetime de Pandas
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [ ]:
# Generamos el esquema de nuevo con los tipos de datos corregidos
esquema_sql = pd.io.sql.get_schema(df, name='yellow_taxi_data', con=engine)
print(esquema_sql)

In [25]:
# df.head(n=0) selecciona 0 filas de datos (solo la cabecera)
# if_exists='replace' asegura que si la tabla ya existía, la borre y empiece de cero
df.head(n=0).to_sql(name='yellow_taxi_data', con=engine, if_exists='replace')
print("Estructura de la tabla creada en PostgreSQL.")

Estructura de la tabla creada en PostgreSQL.

In [26]:
# iterator=True nos permite avanzar manualmente por el archivo
# chunksize=100000 define el tamaño de cada bloque
df_iter = pd.read_csv('yellow_tripdata_2021-01.csv', iterator=True, chunksize=100000)

In [27]:
# 1. Extraer: next() toma el primer bloque de 100k filas del iterador
df = next(df_iter)

# 2. Transformar: Convertimos el texto a fechas reales
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

# 3. Cargar: Enviamos los datos a la tabla. if_exists='append' añade filas nuevas sin borrar lo anterior
%time df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
print("Primer bloque de 100.000 filas insertado exitosamente.")

CPU times: user 3.18 s, sys: 172 ms, total: 3.36 s
Wall time: 5.36 s
Primer bloque de 100.000 filas insertado exitosamente.

In [ ]:
from time import time

# El bucle se repetirá infinitamente hasta que encuentre el error 'StopIteration' (fin del archivo)
while True: 
    try:
        t_start = time()
        
        # 1. Extraer: toma el siguiente bloque de 100k filas
        df = next(df_iter)
        
        # 2. Transformar: convierte el texto a formato fecha
        df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
        df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)
        
        # 3. Cargar: añade los datos a la tabla existente
        df.to_sql(name='yellow_taxi_data', con=engine, if_exists='append')
        
        t_end = time()
        
        print(f"Bloque insertado exitosamente... tomó {t_end - t_start:.3f} segundos")
        
    except StopIteration:
        # Cuando next(df_iter) ya no encuentre más filas, lanzará StopIteration y entraremos aquí
        print("¡Proceso finalizado! Todos los datos han sido insertados en PostgreSQL.")
        break

In [29]:
# 1. Contar el total de registros en la tabla
total_filas = pd.read_sql("SELECT COUNT(*) FROM yellow_taxi_data", con=engine)
print(f"Total de filas en la base de datos: {total_filas.iloc[0,0]}")

# 2. Ver los primeros 5 registros directamente de PostgreSQL
df_postgres = pd.read_sql("SELECT * FROM yellow_taxi_data LIMIT 5", con=engine)
df_postgres

Total de filas en la base de datos: 1369765

,index,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge
0,0,1,2021-01-01 00:30:10,2021-01-01 00:36:12,1,2.10,1,N,142,43,2,8.0,3.0,0.5,0.00,0.0,0.3,11.80,2.5
1,1,1,2021-01-01 00:51:20,2021-01-01 00:52:19,1,0.20,1,N,238,151,2,3.0,0.5,0.5,0.00,0.0,0.3,4.30,0.0
2,2,1,2021-01-01 00:43:30,2021-01-01 01:11:06,1,14.70,1,N,132,165,1,42.0,0.5,0.5,8.65,0.0,0.3,51.95,0.0
3,3,1,2021-01-01 00:15:48,2021-01-01 00:31:01,0,10.60,1,N,138,132,1,29.0,0.5,0.5,6.05,0.0,0.3,36.35,0.0
4,4,2,2021-01-01 00:31:49,2021-01-01 00:48:21,1,4.94,1,N,68,33,1,16.5,0.5,0.5,4.06,0.0,0.3,24.36,2.5